version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/src:cached
      - node_modules:/src/node_modules
    working_dir: "/src"
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
    command: yarn run dev

volumes:
  node_modules: